# Generated by Django 3.2.6 on 2021-08-06 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('sale_choice', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=2)),
                ('houseType', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('TownHouse', 'Townhouse')], default='House', max_length=50)),
                ('sqft', models.IntegerField()),
                ('openHouse', models.BooleanField(default=False)),
                ('photoMain', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo11', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo12', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo13', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo14', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo15', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo16', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo17', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo18', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo19', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo20', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('isPublished', models.BooleanField(default=True)),
                ('listingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
